services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: gp-db

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
    networks:
      - gp-network
    volumes:
      - postgres_data:/var/lib/postgresql

  minio:
    image: minio/minio:latest
    container_name: minio-server
    restart: unless-stopped
    ports:
      - "${MINIO_EXTERNAL_PORT}:${MINIO_INTERNAL_PORT}"
      - "${MINIO_UI_EXTERNAL_PORT}:${MINIO_UI_INTERNAL_PORT}"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_KEY}
    command: server /data --console-address ":${MINIO_UI_INTERNAL_PORT}"
    networks:
      - gp-network

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "${RABBITMQ_EXTERNAL_PORT}:${RABBITMQ_INTERNAL_PORT}"
      - "${RABBITMQ_UI_EXTERNAL_PORT}:${RABBITMQ_UI_INTERNAL_PORT}"
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "+sbwt none +sbwtdcpu none +sbwtdio none"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gp-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context:
        .
    container_name: gp-server
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_INTERNAL_PORT}"
    environment:
      - OTEL_SERVICE_NAME=myservice
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      - db
      - minio
      - rabbitmq
      - otel-collector
    networks:
      - gp-network
    env_file: .env

    restart: on-failure

  otel-collector:
    image: otel/opentelemetry-collector:0.143.0
    container_name: otel-collector
    ports:
      - "4317:4317"
      - "13133:13133"
    command:
      - "--config=/etc/otel-collector-config.yml"
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - gp-network

  loki:
    image: grafana/loki:3.6.3
    container_name: loki
    command:
      - "-config.file=/etc/loki/local-config.yml"
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml:ro
      - loki-data:/loki
    restart: unless-stopped
    networks:
      - gp-network

  grafana:
    image: grafana/grafana:12.3.1
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - gp-network

volumes:
  minio_data:
  rabbitmq_data:
  postgres_data:
  loki-data:
  grafana-data:

networks:
  gp-network:
    driver: bridge
    name: gp-network
