// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/interfaces/interfaces.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	context "context"
	io "io"
	multipart "mime/multipart"
	reflect "reflect"
	uuid "uuid"

	models "github.com/artni96/GophProfile/internal/models"
	gomock "github.com/golang/mock/gomock"
	sqlx "github.com/jmoiron/sqlx"
)

// MockRepositoryI is a mock of RepositoryI interface.
type MockRepositoryI struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryIMockRecorder
}

// MockRepositoryIMockRecorder is the mock recorder for MockRepositoryI.
type MockRepositoryIMockRecorder struct {
	mock *MockRepositoryI
}

// NewMockRepositoryI creates a new mock instance.
func NewMockRepositoryI(ctrl *gomock.Controller) *MockRepositoryI {
	mock := &MockRepositoryI{ctrl: ctrl}
	mock.recorder = &MockRepositoryIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryI) EXPECT() *MockRepositoryIMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockRepositoryI) BeginTx(ctx context.Context) (*sqlx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sqlx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockRepositoryIMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockRepositoryI)(nil).BeginTx), ctx)
}

// CommitTx mocks base method.
func (m *MockRepositoryI) CommitTx(tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTx", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTx indicates an expected call of CommitTx.
func (mr *MockRepositoryIMockRecorder) CommitTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTx", reflect.TypeOf((*MockRepositoryI)(nil).CommitTx), tx)
}

// DeleteAvatarWithThumbnails mocks base method.
func (m *MockRepositoryI) DeleteAvatarWithThumbnails(tx *sqlx.Tx, flt models.AvatarFilters) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatarWithThumbnails", tx, flt)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAvatarWithThumbnails indicates an expected call of DeleteAvatarWithThumbnails.
func (mr *MockRepositoryIMockRecorder) DeleteAvatarWithThumbnails(tx, flt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatarWithThumbnails", reflect.TypeOf((*MockRepositoryI)(nil).DeleteAvatarWithThumbnails), tx, flt)
}

// GetMetadata mocks base method.
func (m *MockRepositoryI) GetMetadata(ctx context.Context, flt models.AvatarFilters) (models.AvatarDBEntity, []models.GetThumbnailMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, flt)
	ret0, _ := ret[0].(models.AvatarDBEntity)
	ret1, _ := ret[1].([]models.GetThumbnailMetadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockRepositoryIMockRecorder) GetMetadata(ctx, flt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockRepositoryI)(nil).GetMetadata), ctx, flt)
}

// GetMetadataList mocks base method.
func (m *MockRepositoryI) GetMetadataList(ctx context.Context, flt models.AvatarFilters) ([]models.AvatarDBEntity, []models.GetThumbnailMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataList", ctx, flt)
	ret0, _ := ret[0].([]models.AvatarDBEntity)
	ret1, _ := ret[1].([]models.GetThumbnailMetadata)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMetadataList indicates an expected call of GetMetadataList.
func (mr *MockRepositoryIMockRecorder) GetMetadataList(ctx, flt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataList", reflect.TypeOf((*MockRepositoryI)(nil).GetMetadataList), ctx, flt)
}

// RollbackTx mocks base method.
func (m *MockRepositoryI) RollbackTx(tx *sqlx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTx", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTx indicates an expected call of RollbackTx.
func (mr *MockRepositoryIMockRecorder) RollbackTx(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockRepositoryI)(nil).RollbackTx), tx)
}

// Save mocks base method.
func (m *MockRepositoryI) Save(ctx context.Context, toUpload models.SaveAvatarRequest) (models.SaveAvatarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, toUpload)
	ret0, _ := ret[0].(models.SaveAvatarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryIMockRecorder) Save(ctx, toUpload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepositoryI)(nil).Save), ctx, toUpload)
}

// SaveThumbnail mocks base method.
func (m *MockRepositoryI) SaveThumbnail(ctx context.Context, tx *sqlx.Tx, t models.SaveThumbnail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveThumbnail", ctx, tx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveThumbnail indicates an expected call of SaveThumbnail.
func (mr *MockRepositoryIMockRecorder) SaveThumbnail(ctx, tx, t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveThumbnail", reflect.TypeOf((*MockRepositoryI)(nil).SaveThumbnail), ctx, tx, t)
}

// UpdateStatus mocks base method.
func (m *MockRepositoryI) UpdateStatus(ctx context.Context, tx *sqlx.Tx, status models.UpdateAvatarStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, tx, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryIMockRecorder) UpdateStatus(ctx, tx, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepositoryI)(nil).UpdateStatus), ctx, tx, status)
}

// MockServiceI is a mock of ServiceI interface.
type MockServiceI struct {
	ctrl     *gomock.Controller
	recorder *MockServiceIMockRecorder
}

// MockServiceIMockRecorder is the mock recorder for MockServiceI.
type MockServiceIMockRecorder struct {
	mock *MockServiceI
}

// NewMockServiceI creates a new mock instance.
func NewMockServiceI(ctrl *gomock.Controller) *MockServiceI {
	mock := &MockServiceI{ctrl: ctrl}
	mock.recorder = &MockServiceIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceI) EXPECT() *MockServiceIMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockServiceI) Delete(ctx context.Context, flt models.AvatarFilters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, flt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceIMockRecorder) Delete(ctx, flt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceI)(nil).Delete), ctx, flt)
}

// DeleteFromS3 mocks base method.
func (m *MockServiceI) DeleteFromS3(ctx context.Context, avatarID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFromS3", ctx, avatarID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFromS3 indicates an expected call of DeleteFromS3.
func (mr *MockServiceIMockRecorder) DeleteFromS3(ctx, avatarID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFromS3", reflect.TypeOf((*MockServiceI)(nil).DeleteFromS3), ctx, avatarID)
}

// Get mocks base method.
func (m *MockServiceI) Get(ctx context.Context, flt models.AvatarFilters, dimensions string) (models.GetAvatarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, flt, dimensions)
	ret0, _ := ret[0].(models.GetAvatarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceIMockRecorder) Get(ctx, flt, dimensions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockServiceI)(nil).Get), ctx, flt, dimensions)
}

// GetMetadata mocks base method.
func (m *MockServiceI) GetMetadata(ctx context.Context, id uuid.UUID) (models.GetAvatarMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, id)
	ret0, _ := ret[0].(models.GetAvatarMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockServiceIMockRecorder) GetMetadata(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockServiceI)(nil).GetMetadata), ctx, id)
}

// GetMetadataList mocks base method.
func (m *MockServiceI) GetMetadataList(ctx context.Context, flt models.AvatarFilters) (models.GetUserAvatarsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataList", ctx, flt)
	ret0, _ := ret[0].(models.GetUserAvatarsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataList indicates an expected call of GetMetadataList.
func (mr *MockServiceIMockRecorder) GetMetadataList(ctx, flt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataList", reflect.TypeOf((*MockServiceI)(nil).GetMetadataList), ctx, flt)
}

// Save mocks base method.
func (m *MockServiceI) Save(ctx context.Context, file multipart.File, header *multipart.FileHeader, userID string) (models.SaveAvatarResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, file, header, userID)
	ret0, _ := ret[0].(models.SaveAvatarResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockServiceIMockRecorder) Save(ctx, file, header, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockServiceI)(nil).Save), ctx, file, header, userID)
}

// UploadThumbnailsToS3 mocks base method.
func (m *MockServiceI) UploadThumbnailsToS3(ctx context.Context, msg models.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadThumbnailsToS3", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadThumbnailsToS3 indicates an expected call of UploadThumbnailsToS3.
func (mr *MockServiceIMockRecorder) UploadThumbnailsToS3(ctx, msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadThumbnailsToS3", reflect.TypeOf((*MockServiceI)(nil).UploadThumbnailsToS3), ctx, msg)
}

// MockS3I is a mock of S3I interface.
type MockS3I struct {
	ctrl     *gomock.Controller
	recorder *MockS3IMockRecorder
}

// MockS3IMockRecorder is the mock recorder for MockS3I.
type MockS3IMockRecorder struct {
	mock *MockS3I
}

// NewMockS3I creates a new mock instance.
func NewMockS3I(ctrl *gomock.Controller) *MockS3I {
	mock := &MockS3I{ctrl: ctrl}
	mock.recorder = &MockS3IMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3I) EXPECT() *MockS3IMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockS3I) Check() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockS3IMockRecorder) Check() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockS3I)(nil).Check))
}

// Delete mocks base method.
func (m *MockS3I) Delete(ctx context.Context, objectKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, objectKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockS3IMockRecorder) Delete(ctx, objectKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockS3I)(nil).Delete), ctx, objectKey)
}

// Get mocks base method.
func (m *MockS3I) Get(ctx context.Context, objectKey string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, objectKey)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockS3IMockRecorder) Get(ctx, objectKey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockS3I)(nil).Get), ctx, objectKey)
}

// GetAddr mocks base method.
func (m *MockS3I) GetAddr() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddr")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAddr indicates an expected call of GetAddr.
func (mr *MockS3IMockRecorder) GetAddr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddr", reflect.TypeOf((*MockS3I)(nil).GetAddr))
}

// GetBucketName mocks base method.
func (m *MockS3I) GetBucketName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBucketName indicates an expected call of GetBucketName.
func (mr *MockS3IMockRecorder) GetBucketName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketName", reflect.TypeOf((*MockS3I)(nil).GetBucketName))
}

// Save mocks base method.
func (m *MockS3I) Save(ctx context.Context, objectKey string, reader io.ReadSeeker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, objectKey, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockS3IMockRecorder) Save(ctx, objectKey, reader interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockS3I)(nil).Save), ctx, objectKey, reader)
}

// MockBrokerI is a mock of BrokerI interface.
type MockBrokerI struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerIMockRecorder
}

// MockBrokerIMockRecorder is the mock recorder for MockBrokerI.
type MockBrokerIMockRecorder struct {
	mock *MockBrokerI
}

// NewMockBrokerI creates a new mock instance.
func NewMockBrokerI(ctrl *gomock.Controller) *MockBrokerI {
	mock := &MockBrokerI{ctrl: ctrl}
	mock.recorder = &MockBrokerIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerI) EXPECT() *MockBrokerIMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockBrokerI) Check() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check")
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockBrokerIMockRecorder) Check() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockBrokerI)(nil).Check))
}

// Produce mocks base method.
func (m_2 *MockBrokerI) Produce(ctx context.Context, m models.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Produce", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockBrokerIMockRecorder) Produce(ctx, m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockBrokerI)(nil).Produce), ctx, m)
}
